require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: '3.0.0'
  NewCops: enable

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/GuardClause:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 1
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
