require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: '2.5.0'
  NewCops: enable

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 1
