name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.6, 2.7]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby ${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install bundler
        run: gem install --no-document bundler:2.1.4

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: rake
